spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

logging:
  level:
    com:
      example: debug
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        cloud:
          sleuth: info