spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/svc_a
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
#      server-addr: 127.0.0.1:8848
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
#  service:
#    vgroup-mapping:
#      default_tx_group: "default"


logging:
  pattern:
    # 日志输出格式
    console: "%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) [%thread] %clr(%logger){cyan} : %msg%n"
  level:
    com:
      example: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
        cloud:
          sleuth: info
    io:
      seata: info