spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/svc_c
    username: root
    password: admin
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true

logging:
  level:
    com:
      example: debug
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: info
        cloud:
          sleuth: info