spring:
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1
server:
  port: 1013

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      version: "v1.0.0"

logging:
  level:
    cn:
      com:
        yusys:
          lbswitch: debug
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
        cloud:
          sleuth: info