spring:
  devtools:
    restart:
      additional-paths: /Users/zqy/test/classes/

server:
  port: 1011

management:
  endpoints:
    web:
      exposure:
        include: env,beans

logging:
  level:
    org:
      springframework:
        boot:
          devtools: debug

