spring:
  application:
    name: gateway-zuul
server:
  port: 80
  tomcat:
    max-connections: 10000
    accept-count: 10000
    max-threads: 2000

zuul:
  host:
    max-per-route-connections: 20
    max-total-connections: 20000
  semaphore:
    max-semaphores: 5000



eureka:
  instance:
    metadata-map:
      version: "Greenwich.SR1"
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  #Ribbon允许最大连接数，即所有后端微服务实例请求并发数之和的最大值。
  MaxTotalConnections: 500
  #单个后端微服务实例能接收的最大请求并发数
  MaxConnectionsPerHost: 500
  #建议设置超时时间，以免因为等待时间过长造成请求处理失败（一）
  #Http请求中的socketTimeout
  ReadTimeout: 5000
  #Http请求中的connectTimeout
  ConnectTimeout: 10000

logging:
  level:
    root: error